CREATE TABLE CONT
(
	CONT_ID INT PRIMARY KEY IDENTITY (1,1),
	CONT_NUMB NVARCHAR(500) NOT NULL,
	CONT_STRT_DTE DATETIME NULL,
	CONT_END_DTE DATETIME NULL,
	INSR_BY VARCHAR(500) DEFAULT ORIGINAL_LOGIN(),
	INSR_DTE VARCHAR(500) DEFAULT GETDATE(),
	UPDT_BY VARCHAR(500) DEFAULT ORIGINAL_LOGIN(),
	UPDT_DTE VARCHAR(500) DEFAULT GETDATE()
)

CREATE TABLE CONT_ASET
(
	CONT_ASET_ID INT PRIMARY KEY IDENTITY (1,1),
	CONT_ID INT NOT NULL,
	VIN_NUMB NVARCHAR(500) NOT NULL,
	MODL_NME NVARCHAR(500) NOT NULL,
	INSR_BY VARCHAR(500) DEFAULT ORIGINAL_LOGIN(),
	INSR_DTE VARCHAR(500) DEFAULT GETDATE(),
	UPDT_BY VARCHAR(500) DEFAULT ORIGINAL_LOGIN(),
	UPDT_DTE VARCHAR(500) DEFAULT GETDATE(),
	FOREIGN KEY (CONT_ID) REFERENCES CONT(CONT_ID)
)
