version: "3.9"
services:
    contract-activation-service:
        build: ContractActivationService\ContractActivationService\app\publish
        ports:
            - "5001:80"

    contract-modification-service:
        build: ContractModificationService\app\publish
        ports:
            - "5002:80"